//! Sigma Protocol — Zero-Knowledge Proof of Key Possession (§3.5.4)
//!
//! # What is the Sigma Protocol?
//!
//! During pairing, both parties prove they possess the private key
//! corresponding to the public key they presented.  This prevents an
//! attacker from impersonating someone by presenting a stolen public key.
//!
//! We implement a **non-interactive challenge-response** construction that
//! achieves the same security goal (proof of key possession) using Ed25519
//! signatures, which are already available throughout the stack.
//!
//! # Protocol
//!
//! ```text
//! 1. COMMIT:    Prover generates a fresh random nonce N (32 bytes).
//!               Sends N to verifier.
//!
//! 2. CHALLENGE: Verifier generates a fresh random challenge C (32 bytes).
//!               Sends C to prover.
//!
//! 3. RESPOND:   Prover computes a signature over
//!               b"meshinfinity-sigma-v1" || N || C
//!               using their Ed25519 identity key.
//!               Sends 64-byte signature S to verifier.
//!
//! 4. VERIFY:    Verifier checks S against the prover's known public key
//!               over the same message: b"meshinfinity-sigma-v1" || N || C.
//!               If valid → prover holds the private key.
//!               If invalid → reject.
//! ```
//!
//! # Security Properties
//!
//! - **Proof of key possession:** a valid signature requires the private key.
//! - **Replay protection:** the response is bound to the verifier's fresh
//!   challenge C; a transcript with challenge C′ ≠ C cannot be reused.
//! - **Forward binding:** the nonce N (chosen by the prover before seeing C)
//!   prevents the verifier from pre-computing a matching challenge.
//! - **Protocol binding:** the domain prefix
//!   `b"meshinfinity-sigma-v1"` prevents cross-protocol signature reuse.
//!
//! # Deniability Note
//!
//! Ed25519 signatures are non-repudiable by themselves.  However, this
//! protocol runs inside an ephemeral WireGuard session (§3.5.4), so the
//! transcript is not visible to third parties — only the two pairing peers
//! observe it.  The encrypted channel provides the operational deniability
//! required by §3.5.
//!
//! # Why Not Pure Schnorr?
//!
//! A pure Schnorr Σ-protocol requires direct access to the Ed25519 scalar
//! (the clamped SHA-512 expansion of the seed), which `ed25519-dalek` does
//! not expose in its public API.  The signature-based construction used here
//! is cryptographically equivalent for the proof-of-possession goal and avoids
//! fragile internals while reusing the audited signing path.

use ed25519_dalek::{Signature, Signer, SigningKey, Verifier, VerifyingKey};
use rand_core::{OsRng, RngCore};

// ─────────────────────────────────────────────────────────────────────────────
// Domain tag
// ─────────────────────────────────────────────────────────────────────────────

/// Protocol domain separator — included in every signed message to prevent
/// cross-protocol reuse of Sigma transcripts.
const SIGMA_DOMAIN: &[u8] = b"meshinfinity-sigma-v1";

// ─────────────────────────────────────────────────────────────────────────────
// Error types
// ─────────────────────────────────────────────────────────────────────────────

/// Errors during Sigma protocol execution.
#[derive(Debug, thiserror::Error)]
pub enum SigmaError {
    /// The verifier's signature check failed.
    ///
    /// Either the prover does not hold the claimed private key, or the
    /// transcript was corrupted in transit.
    #[error("Sigma verification failed — prover does not hold the private key")]
    VerificationFailed,

    /// The prover's claimed public key is malformed (not a valid Ed25519 key).
    #[error("Sigma public key is invalid")]
    InvalidPublicKey,
}

// ─────────────────────────────────────────────────────────────────────────────
// Protocol messages
// ─────────────────────────────────────────────────────────────────────────────

/// Step 1: Prover's commitment (prover → verifier).
///
/// A fresh random nonce generated by the prover before seeing the challenge.
/// Binds the response to a specific protocol run and prevents the verifier
/// from pre-selecting a challenge that would match a pre-computed response.
#[derive(Clone)]
pub struct SigmaCommitment {
    /// 32-byte random nonce, generated fresh per protocol run.
    pub commitment: [u8; 32],
}

/// Step 2: Verifier's challenge (verifier → prover).
///
/// A fresh random 32-byte value that the prover must incorporate into
/// their response.  Prevents replay of previously recorded transcripts.
pub struct SigmaChallenge {
    /// 32-byte fresh random challenge.
    pub challenge: [u8; 32],
}

/// Step 3: Prover's response (prover → verifier).
///
/// An Ed25519 signature over `SIGMA_DOMAIN || commitment.nonce || challenge`.
/// 64 bytes.
pub struct SigmaResponse {
    /// Ed25519 signature bytes (64 bytes).
    pub response: [u8; 64],
}

// ─────────────────────────────────────────────────────────────────────────────
// Prover side
// ─────────────────────────────────────────────────────────────────────────────

/// The prover's state during the Sigma protocol.
///
/// Created at Step 1 (commitment generation), consumed at Step 3 (response).
pub struct SigmaProver {
    /// The nonce N sent to the verifier as the commitment.
    pub commitment: SigmaCommitment,
}

impl SigmaProver {
    /// Step 1: Generate a fresh commitment nonce.
    ///
    /// The prover sends `commitment` to the verifier before the challenge
    /// is known.
    pub fn new() -> Self {
        let mut nonce = [0u8; 32];
        OsRng.fill_bytes(&mut nonce);
        SigmaProver {
            commitment: SigmaCommitment { commitment: nonce },
        }
    }

    /// Step 3: Produce a response to the verifier's challenge.
    ///
    /// Signs `SIGMA_DOMAIN || commitment_nonce || challenge` using the
    /// provided `signing_key`.  Consuming `self` ensures the commitment
    /// nonce is not reused.
    pub fn respond(self, challenge: &SigmaChallenge, signing_key: &SigningKey) -> SigmaResponse {
        let msg = build_signed_message(&self.commitment.commitment, &challenge.challenge);
        let sig: Signature = signing_key.sign(&msg);
        SigmaResponse {
            response: sig.to_bytes(),
        }
    }
}

impl Default for SigmaProver {
    fn default() -> Self {
        Self::new()
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Verifier side
// ─────────────────────────────────────────────────────────────────────────────

/// The verifier's state during the Sigma protocol.
pub struct SigmaVerifier {
    /// The challenge we sent to the prover.
    challenge: SigmaChallenge,
    /// The prover's commitment nonce we received.
    prover_commitment: SigmaCommitment,
    /// The prover's claimed Ed25519 public key.
    prover_public_key: [u8; 32],
}

impl SigmaVerifier {
    /// Step 2: Accept the prover's commitment and generate a challenge.
    ///
    /// The generated challenge must be sent to the prover before calling
    /// `verify()`.
    pub fn new(commitment: SigmaCommitment, prover_public_key: [u8; 32]) -> Self {
        let mut challenge_bytes = [0u8; 32];
        OsRng.fill_bytes(&mut challenge_bytes);

        SigmaVerifier {
            challenge: SigmaChallenge { challenge: challenge_bytes },
            prover_commitment: commitment,
            prover_public_key,
        }
    }

    /// Get the challenge to send to the prover.
    pub fn challenge(&self) -> &SigmaChallenge {
        &self.challenge
    }

    /// Step 4: Verify the prover's response.
    ///
    /// Verifies that the 64-byte signature in `response` is a valid Ed25519
    /// signature over `SIGMA_DOMAIN || commitment || challenge` produced by
    /// the private key corresponding to `prover_public_key`.
    ///
    /// Returns `Ok(())` on success.
    /// Returns `Err(SigmaError::VerificationFailed)` if the signature is wrong.
    /// Returns `Err(SigmaError::InvalidPublicKey)` if the public key is malformed.
    pub fn verify(self, response: &SigmaResponse) -> Result<(), SigmaError> {
        // Parse the claimed public key.
        let verifying_key = VerifyingKey::from_bytes(&self.prover_public_key)
            .map_err(|_| SigmaError::InvalidPublicKey)?;

        // Parse the 64-byte signature.
        let signature = Signature::from_bytes(&response.response);

        // Reconstruct the message the prover signed.
        let msg = build_signed_message(
            &self.prover_commitment.commitment,
            &self.challenge.challenge,
        );

        // Verify the signature.  This is a complete Ed25519 verification —
        // not a length check.  Invalid signatures fail cryptographically.
        verifying_key
            .verify(&msg, &signature)
            .map_err(|_| SigmaError::VerificationFailed)
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Helper
// ─────────────────────────────────────────────────────────────────────────────

/// Build the message that the prover signs and the verifier reconstructs.
///
/// `SIGMA_DOMAIN || nonce || challenge`
fn build_signed_message(nonce: &[u8; 32], challenge: &[u8; 32]) -> Vec<u8> {
    let mut msg = Vec::with_capacity(SIGMA_DOMAIN.len() + 64);
    msg.extend_from_slice(SIGMA_DOMAIN);
    msg.extend_from_slice(nonce);
    msg.extend_from_slice(challenge);
    msg
}

// ─────────────────────────────────────────────────────────────────────────────
// Convenience: run both sides of the protocol
// ─────────────────────────────────────────────────────────────────────────────

/// Run a complete Sigma protocol between a local prover and verifier.
///
/// Used in the pairing flow (§8.3) — both parties run this simultaneously
/// (each proves to the other).
///
/// Returns `Ok(())` if the prover successfully demonstrated possession of
/// the private key corresponding to `prover_pub_key`.
pub fn sigma_prove_and_verify(
    prover_signing_key: &SigningKey,
    prover_pub_key: &[u8; 32],
) -> Result<(), SigmaError> {
    // Step 1: Prover generates commitment.
    let prover = SigmaProver::new();
    let commitment = prover.commitment.clone();

    // Step 2: Verifier receives commitment and generates challenge.
    let verifier = SigmaVerifier::new(commitment, *prover_pub_key);
    let challenge = SigmaChallenge {
        challenge: verifier.challenge().challenge,
    };

    // Step 3: Prover computes response.
    let response = prover.respond(&challenge, prover_signing_key);

    // Step 4: Verifier checks response.
    verifier.verify(&response)
}

// ─────────────────────────────────────────────────────────────────────────────
// Tests
// ─────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    // ── Correctness ──────────────────────────────────────────────────────────

    #[test]
    fn sigma_protocol_succeeds_for_honest_prover() {
        let signing_key = SigningKey::generate(&mut OsRng);
        let pub_key = signing_key.verifying_key().to_bytes();
        let result = sigma_prove_and_verify(&signing_key, &pub_key);
        assert!(result.is_ok(), "honest prover must succeed: {result:?}");
    }

    #[test]
    fn sigma_mutual_proof_alice_and_bob() {
        let alice_sk = SigningKey::generate(&mut OsRng);
        let alice_pub = alice_sk.verifying_key().to_bytes();

        let bob_sk = SigningKey::generate(&mut OsRng);
        let bob_pub = bob_sk.verifying_key().to_bytes();

        assert!(sigma_prove_and_verify(&alice_sk, &alice_pub).is_ok());
        assert!(sigma_prove_and_verify(&bob_sk, &bob_pub).is_ok());
    }

    // ── Security: reject forgery ─────────────────────────────────────────────

    /// An attacker who doesn't have the private key for pub_key cannot
    /// produce a valid response.  They sign with a DIFFERENT key and the
    /// verifier must reject.
    #[test]
    fn sigma_rejects_wrong_signing_key() {
        let legitimate_sk = SigningKey::generate(&mut OsRng);
        let legitimate_pub = legitimate_sk.verifying_key().to_bytes();

        let attacker_sk = SigningKey::generate(&mut OsRng);

        // Attacker presents legitimate_pub but signs with attacker_sk.
        let prover = SigmaProver::new();
        let commitment = prover.commitment.clone();
        let verifier = SigmaVerifier::new(commitment, legitimate_pub);
        let challenge = SigmaChallenge {
            challenge: verifier.challenge().challenge,
        };
        let forged_response = prover.respond(&challenge, &attacker_sk);

        let result = verifier.verify(&forged_response);
        assert!(
            matches!(result, Err(SigmaError::VerificationFailed)),
            "wrong signing key must be rejected"
        );
    }

    /// Replaying a valid response from a previous run must be rejected because
    /// the challenge is different.
    #[test]
    fn sigma_rejects_replayed_response() {
        let signing_key = SigningKey::generate(&mut OsRng);
        let pub_key = signing_key.verifying_key().to_bytes();

        // First run — record the response.
        let prover1 = SigmaProver::new();
        let commitment1 = prover1.commitment.clone();
        let verifier1 = SigmaVerifier::new(commitment1.clone(), pub_key);
        let challenge1 = SigmaChallenge { challenge: verifier1.challenge().challenge };
        let response1 = prover1.respond(&challenge1, &signing_key);

        // Second run — use a different verifier (different challenge).
        // Use the same commitment to isolate the replay scenario.
        let verifier2 = SigmaVerifier::new(commitment1, pub_key);
        let different_challenge = verifier2.challenge().challenge;
        // Ensure the challenges are different (overwhelmingly likely).
        assert_ne!(challenge1.challenge, different_challenge,
            "test assumption: fresh challenges must differ");

        // Attempt to reuse response1 against the new challenge.
        let result = verifier2.verify(&response1);
        assert!(
            matches!(result, Err(SigmaError::VerificationFailed)),
            "replayed response must be rejected"
        );
    }

    /// A zeroed response (all zeros) must be rejected.
    #[test]
    fn sigma_rejects_all_zero_response() {
        let signing_key = SigningKey::generate(&mut OsRng);
        let pub_key = signing_key.verifying_key().to_bytes();

        let prover = SigmaProver::new();
        let commitment = prover.commitment.clone();
        let verifier = SigmaVerifier::new(commitment, pub_key);

        let zero_response = SigmaResponse { response: [0u8; 64] };
        let result = verifier.verify(&zero_response);
        assert!(
            matches!(result, Err(SigmaError::VerificationFailed)),
            "all-zero response must be rejected"
        );
    }

    /// A randomly-forged response must be rejected (with overwhelming probability).
    #[test]
    fn sigma_rejects_random_response() {
        let signing_key = SigningKey::generate(&mut OsRng);
        let pub_key = signing_key.verifying_key().to_bytes();

        let prover = SigmaProver::new();
        let commitment = prover.commitment.clone();
        let verifier = SigmaVerifier::new(commitment, pub_key);

        let mut random_response = [0u8; 64];
        OsRng.fill_bytes(&mut random_response);
        let result = verifier.verify(&SigmaResponse { response: random_response });
        assert!(
            matches!(result, Err(SigmaError::VerificationFailed)),
            "random response must be rejected"
        );
    }

    /// The verifier must reject a malformed (not-a-valid-Ed25519-point) public key.
    #[test]
    fn sigma_rejects_malformed_public_key() {
        let signing_key = SigningKey::generate(&mut OsRng);

        let prover = SigmaProver::new();
        let commitment = prover.commitment.clone();
        // A public key of all 0xFF bytes is not a valid Ed25519 point.
        let bad_pub_key = [0xFF_u8; 32];
        let verifier = SigmaVerifier::new(commitment, bad_pub_key);

        let challenge = SigmaChallenge { challenge: verifier.challenge().challenge };
        let response = prover.respond(&challenge, &signing_key);

        let result = verifier.verify(&response);
        assert!(
            matches!(result, Err(SigmaError::InvalidPublicKey | SigmaError::VerificationFailed)),
            "malformed public key must be rejected: {result:?}"
        );
    }

    // ── Structural properties ────────────────────────────────────────────────

    #[test]
    fn commitment_is_unique_per_run() {
        let p1 = SigmaProver::new();
        let p2 = SigmaProver::new();
        assert_ne!(
            p1.commitment.commitment, p2.commitment.commitment,
            "each protocol run must produce a different commitment"
        );
    }

    #[test]
    fn response_differs_for_different_challenges() {
        let signing_key = SigningKey::generate(&mut OsRng);

        let nonce = [0x42u8; 32];
        let c1 = SigmaChallenge { challenge: [0x01u8; 32] };
        let c2 = SigmaChallenge { challenge: [0x02u8; 32] };

        let p1 = SigmaProver {
            commitment: SigmaCommitment { commitment: nonce },
        };
        let p2 = SigmaProver {
            commitment: SigmaCommitment { commitment: nonce },
        };

        let r1 = p1.respond(&c1, &signing_key);
        let r2 = p2.respond(&c2, &signing_key);
        assert_ne!(r1.response, r2.response,
            "different challenges must produce different responses");
    }

    #[test]
    fn response_differs_for_different_keys() {
        let sk1 = SigningKey::generate(&mut OsRng);
        let sk2 = SigningKey::generate(&mut OsRng);

        let nonce = [0x11u8; 32];
        let challenge = SigmaChallenge { challenge: [0x22u8; 32] };

        let p1 = SigmaProver { commitment: SigmaCommitment { commitment: nonce } };
        let p2 = SigmaProver { commitment: SigmaCommitment { commitment: nonce } };

        let r1 = p1.respond(&challenge, &sk1);
        let r2 = p2.respond(&challenge, &sk2);
        assert_ne!(r1.response, r2.response,
            "different signing keys must produce different responses");
    }
}
