//! Key Change Validation (§4.6)
//!
//! # What is key change validation?
//!
//! When a peer's identity keys change (device loss, replacement, compromise),
//! the system must prevent silent key substitution by an attacker. This module
//! implements the three-layer verification model:
//!
//! 1. **Cryptographic proof**: the OLD key signs the NEW keys, proving the
//!    holder of the old key authorized the transition. Highest confidence.
//! 2. **Passphrase proof**: an Argon2id-hashed passphrase shared out-of-band
//!    during initial pairing. Medium confidence.
//! 3. **No proof**: neither signature nor passphrase is available. The contact
//!    must manually accept or reject the change. Lowest confidence.
//!
//! # 72-hour waiting period
//!
//! All key changes — even those with cryptographic proof — enforce a 72-hour
//! grace period before the new key is trusted. This gives contacts time to
//! detect and reject a compromised key change before it takes effect.
//!
//! # Workflow
//!
//! 1. The peer changing keys calls `create_key_change_request()`.
//! 2. The request is sent to all contacts.
//! 3. Each contact calls `validate_key_change()` to assess proof level.
//! 4. The 72-hour timer starts. Contacts can `accept_key_change()` or
//!    `reject_key_change()` during this window.
//! 5. After 72h, `check_key_change_expiry()` auto-accepts if no action taken.

use argon2::{Algorithm, Argon2, Params, Version};
use serde::{Deserialize, Serialize};

use crate::crypto::signing::{self, DOMAIN_KEY_CHANGE};
use crate::error::MeshError;
use crate::identity::peer_id::PeerId;

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/// The 72-hour waiting period in seconds (§4.6).
/// All key changes must wait this long before being trusted,
/// giving contacts time to detect and reject compromised changes.
const GRACE_PERIOD_SECS: u64 = 72 * 60 * 60;

/// Argon2id memory cost for key change passphrase hashing.
/// 64 MB — same as PIN derivation (§3.7.4) for consistency.
const ARGON2_M_COST: u32 = 65536;

/// Argon2id time cost (iteration count) for passphrase hashing.
/// 3 iterations — spec minimum for interactive use cases.
const ARGON2_T_COST: u32 = 3;

/// Argon2id parallelism for passphrase hashing.
/// 4 lanes — balances speed vs. memory-hardness on typical hardware.
const ARGON2_P_COST: u32 = 4;

/// Output length for the Argon2id passphrase hash.
/// 32 bytes — sufficient for comparing verification hashes.
const ARGON2_OUTPUT_LEN: usize = 32;

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/// A key change request from a peer (§4.6).
///
/// Created when a peer's identity keys change (device loss, replacement,
/// or deliberate rotation). Contains all the information needed for
/// contacts to verify the legitimacy of the change.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct KeyChangeRequest {
    /// The peer whose keys are changing.
    /// Used to look up the existing contact record for verification.
    pub peer_id: PeerId,

    /// The OLD Ed25519 public key (for verification against stored key).
    /// Must match what the contact has on record, or the request is suspicious.
    pub old_ed_pub: [u8; 32],

    /// The NEW Ed25519 public key that the peer wants to transition to.
    /// Will replace old_ed_pub in the contact record after acceptance.
    pub new_ed_pub: [u8; 32],

    /// The NEW X25519 public key for Diffie-Hellman key agreement.
    /// Will replace the old X25519 key in the contact record after acceptance.
    pub new_x25519_pub: [u8; 32],

    /// Proof: signature by the OLD key over (new_ed_pub || new_x25519_pub || timestamp).
    /// If the old key is compromised, this will be absent and the change requires
    /// manual verification by contacts. Provides highest confidence of continuity.
    pub old_key_signature: Option<Vec<u8>>,

    /// Argon2id hash of a passphrase shared out-of-band (for verification
    /// when the old key is unavailable). Medium confidence — proves knowledge
    /// of the shared secret agreed upon during initial pairing.
    pub passphrase_hash: Option<Vec<u8>>,

    /// The salt used for Argon2id passphrase hashing.
    /// Required when passphrase_hash is present; ignored otherwise.
    /// 16 bytes, randomly generated by the key change initiator.
    pub passphrase_salt: Option<[u8; 16]>,

    /// When this request was created (Unix timestamp).
    /// Used as input to the signature message to prevent replay.
    pub requested_at: u64,

    /// Current status of this key change request.
    /// Transitions: Pending -> Accepted | Rejected | AutoAccepted.
    pub status: KeyChangeStatus,
}

/// The lifecycle status of a key change request.
///
/// A request starts as Pending with a 72-hour expiry timer. It can be
/// explicitly accepted or rejected by the contact, or auto-accepted
/// when the grace period expires without action.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum KeyChangeStatus {
    /// Waiting for the 72-hour grace period to expire.
    /// `expires_at` is the Unix timestamp when auto-acceptance occurs.
    Pending {
        /// Unix timestamp when the grace period ends.
        expires_at: u64,
    },

    /// The contact has explicitly accepted the key change.
    /// The new keys should now replace the old ones in the contact record.
    Accepted,

    /// The contact has explicitly rejected the key change.
    /// The peer's keys remain unchanged; possible MITM detected.
    Rejected,

    /// The grace period expired and the change was auto-accepted.
    /// Treated the same as Accepted, but distinguishable for audit.
    AutoAccepted,
}

/// The result of validating a key change request.
///
/// Indicates the confidence level of the key change's legitimacy.
/// All levels still enforce the 72-hour waiting period — the difference
/// is whether the contact is prompted for manual action.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum KeyChangeValidation {
    /// Old key signed the new key — high confidence, still enforce 72h wait.
    /// The holder of the old key explicitly authorized this transition.
    CryptographicProof,

    /// Passphrase matches — medium confidence, enforce 72h wait.
    /// The requester proved knowledge of the shared out-of-band secret.
    PassphraseProof,

    /// No proof available — low confidence, require manual acceptance.
    /// The contact must verify through an out-of-band channel.
    NoProof,
}

// ---------------------------------------------------------------------------
// Key Change Creation
// ---------------------------------------------------------------------------

/// Create a key change request (called by the peer changing their keys).
///
/// Signs the new keys with the old key if `old_secret` is available.
/// If the old key is lost/compromised, pass `None` for `old_secret`
/// and optionally provide a passphrase for out-of-band verification.
///
/// # Arguments
///
/// * `old_secret` — the 32-byte Ed25519 secret key (if still available).
/// * `new_ed_pub` — the new Ed25519 public key to transition to.
/// * `new_x25519_pub` — the new X25519 public key for key agreement.
/// * `passphrase` — optional shared passphrase for out-of-band proof.
///
/// # Errors
///
/// Returns `MeshError::Internal` if Argon2id hashing fails (should not
/// happen with valid parameters, but we never unwrap).
pub fn create_key_change_request(
    old_secret: Option<&[u8; 32]>,
    new_ed_pub: &[u8; 32],
    new_x25519_pub: &[u8; 32],
    passphrase: Option<&str>,
) -> Result<KeyChangeRequest, MeshError> {
    // Get the current Unix timestamp for the request.
    // Uses SystemTime which is monotonic enough for our purposes.
    let now = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map_err(|e| MeshError::Internal(format!("system clock error: {e}")))?
        .as_secs();

    // Build the message to sign: new_ed_pub || new_x25519_pub || timestamp.
    // This binds the signature to both new keys AND the timestamp,
    // preventing an attacker from replaying an old key change signature.
    let mut sign_message = Vec::with_capacity(32 + 32 + 8);
    sign_message.extend_from_slice(new_ed_pub);
    sign_message.extend_from_slice(new_x25519_pub);
    sign_message.extend_from_slice(&now.to_le_bytes());

    // If we have the old secret key, sign the new keys to prove continuity.
    // This is the strongest form of proof — the holder of the old key
    // explicitly authorized the transition to the new keys.
    let old_key_signature = old_secret.map(|secret| {
        signing::sign(secret, DOMAIN_KEY_CHANGE, &sign_message)
    });

    // Derive the old Ed25519 public key from the secret, if available.
    // If the old key is lost, we use a zero placeholder — the contact
    // will compare against their stored key to detect mismatches.
    let old_ed_pub = match old_secret {
        Some(secret) => {
            // Derive the public key from the secret key for the request.
            let signing_key = ed25519_dalek::SigningKey::from_bytes(secret);
            signing_key.verifying_key().to_bytes()
        }
        // Old key is unavailable — zero placeholder signals this to contacts.
        None => [0u8; 32],
    };

    // If a passphrase is provided, hash it with Argon2id for out-of-band
    // verification. Generate a fresh random salt for each request.
    let (passphrase_hash, passphrase_salt) = match passphrase {
        Some(phrase) => {
            // Generate a cryptographically random 16-byte salt.
            let mut salt = [0u8; 16];
            rand_core::OsRng.fill_bytes(&mut salt);

            // Hash the passphrase using Argon2id with the generated salt.
            let hash = hash_key_change_passphrase(phrase, &salt)?;
            (Some(hash), Some(salt))
        }
        // No passphrase — both fields are None.
        None => (None, None),
    };

    // The grace period starts now and expires after 72 hours.
    // During this window, contacts can accept or reject the change.
    let expires_at = now + GRACE_PERIOD_SECS;

    // Assemble the complete key change request.
    Ok(KeyChangeRequest {
        peer_id: PeerId::from_ed25519_pub(&old_ed_pub),
        old_ed_pub,
        new_ed_pub: *new_ed_pub,
        new_x25519_pub: *new_x25519_pub,
        old_key_signature,
        passphrase_hash,
        passphrase_salt,
        requested_at: now,
        status: KeyChangeStatus::Pending { expires_at },
    })
}

// ---------------------------------------------------------------------------
// Key Change Validation
// ---------------------------------------------------------------------------

/// Validate an incoming key change request from a contact.
///
/// Checks three levels of proof in descending confidence:
/// 1. Old key signature (if present) — cryptographic proof of continuity
/// 2. Passphrase verification (if provided) — out-of-band proof
/// 3. No proof available — require manual acceptance
///
/// All levels start the 72-hour waiting period. The difference is the
/// confidence level returned, which the UI uses to decide how urgently
/// to prompt the user.
///
/// # Arguments
///
/// * `request` — the incoming key change request to validate.
/// * `known_old_pub` — the Ed25519 public key we have on file for this peer.
///
/// # Errors
///
/// Returns `MeshError::InvalidSignature` if the old key signature is present
/// but fails verification (possible MITM or tampering).
/// Returns `MeshError::InvalidKey` if the claimed old key doesn't match
/// our records.
pub fn validate_key_change(
    request: &KeyChangeRequest,
    known_old_pub: &[u8; 32],
) -> Result<KeyChangeValidation, MeshError> {
    // Step 1: Verify the claimed old public key matches what we have on file.
    // A mismatch means either the request is forged or our records are stale.
    // We allow all-zero old_ed_pub as a signal that the old key is unavailable.
    let old_key_available = request.old_ed_pub != [0u8; 32];

    // If the old key is provided in the request, it MUST match our records.
    // An attacker cannot claim a different old key than what we know.
    if old_key_available && request.old_ed_pub != *known_old_pub {
        return Err(MeshError::InvalidKey(
            "old public key in request does not match stored key".to_string(),
        ));
    }

    // Step 2: Check cryptographic proof — old key signature over new keys.
    // This is the strongest proof because only the holder of the old private
    // key could produce a valid signature.
    if let Some(ref sig_bytes) = request.old_key_signature {
        // Reconstruct the signed message: new_ed_pub || new_x25519_pub || timestamp.
        // Must match exactly what create_key_change_request() signed.
        let mut sign_message = Vec::with_capacity(32 + 32 + 8);
        sign_message.extend_from_slice(&request.new_ed_pub);
        sign_message.extend_from_slice(&request.new_x25519_pub);
        sign_message.extend_from_slice(&request.requested_at.to_le_bytes());

        // Verify the signature against the known old public key.
        // Use the domain separator to prevent cross-protocol replay.
        let valid = signing::verify(
            known_old_pub,
            DOMAIN_KEY_CHANGE,
            &sign_message,
            sig_bytes,
        );

        // A present-but-invalid signature is a security event.
        // An attacker may have forged the request or the key is compromised.
        if !valid {
            return Err(MeshError::InvalidSignature);
        }

        // Signature verified — this is high-confidence proof of continuity.
        return Ok(KeyChangeValidation::CryptographicProof);
    }

    // Step 3: Check passphrase proof — Argon2id hash of shared secret.
    // This is medium confidence because it proves knowledge of the passphrase
    // agreed during initial pairing, but does not prove key continuity.
    if request.passphrase_hash.is_some() {
        // Passphrase proof is present. The contact must verify it against
        // their stored verification passphrase using verify_passphrase_hash().
        // We return PassphraseProof to indicate the proof type is available;
        // the actual passphrase comparison happens at a higher layer where
        // the contact's stored passphrase is accessible.
        return Ok(KeyChangeValidation::PassphraseProof);
    }

    // Step 4: No proof available — lowest confidence.
    // The contact must manually verify through an out-of-band channel
    // (e.g., phone call, in-person meeting) before accepting.
    Ok(KeyChangeValidation::NoProof)
}

// ---------------------------------------------------------------------------
// Key Change Actions
// ---------------------------------------------------------------------------

/// Accept a pending key change (contact approves).
///
/// Transitions the request from Pending to Accepted. After acceptance,
/// the caller should update the contact record with the new keys.
/// Only valid when the request is in Pending status.
pub fn accept_key_change(request: &mut KeyChangeRequest) {
    // Only transition from Pending — other states are terminal.
    // Accepting an already-accepted or rejected request is a no-op.
    if matches!(request.status, KeyChangeStatus::Pending { .. }) {
        request.status = KeyChangeStatus::Accepted;
    }
}

/// Reject a pending key change (contact rejects — possible MITM).
///
/// Transitions the request from Pending to Rejected. The peer's keys
/// remain unchanged in the contact record. The contact should be
/// alerted that a suspicious key change was attempted.
pub fn reject_key_change(request: &mut KeyChangeRequest) {
    // Only transition from Pending — other states are terminal.
    // Rejecting an already-accepted change does not revert it.
    if matches!(request.status, KeyChangeStatus::Pending { .. }) {
        request.status = KeyChangeStatus::Rejected;
    }
}

/// Check if a pending key change's 72h wait has expired.
///
/// If the grace period has elapsed and the request is still Pending,
/// it is auto-accepted. This prevents key changes from being stuck
/// in limbo if the contact doesn't respond.
///
/// # Arguments
///
/// * `request` — the key change request to check.
/// * `now_unix` — current Unix timestamp for comparison.
pub fn check_key_change_expiry(request: &mut KeyChangeRequest, now_unix: u64) {
    // Only auto-accept if still Pending and the timer has expired.
    // Already-accepted or rejected requests are not modified.
    if let KeyChangeStatus::Pending { expires_at } = request.status {
        // Compare current time against the expiry deadline.
        // If now >= expires_at, the 72-hour window has closed.
        if now_unix >= expires_at {
            request.status = KeyChangeStatus::AutoAccepted;
        }
    }
}

// ---------------------------------------------------------------------------
// Passphrase Hashing
// ---------------------------------------------------------------------------

/// Derive the Argon2id hash for key change passphrase verification.
///
/// Uses the same Argon2id parameters as PIN derivation (§3.7.4) for
/// consistency: 64 MB memory, 3 iterations, 4 lanes.
///
/// # Arguments
///
/// * `passphrase` — the shared passphrase string to hash.
/// * `salt` — a 16-byte salt (randomly generated per request).
///
/// # Errors
///
/// Returns `MeshError::Internal` if the Argon2id computation fails
/// (should never happen with valid parameters, but we avoid unwrap).
pub fn hash_key_change_passphrase(
    passphrase: &str,
    salt: &[u8; 16],
) -> Result<Vec<u8>, MeshError> {
    // Build the Argon2id instance with spec-mandated parameters.
    // Algorithm::Argon2id is the recommended variant — resistant to both
    // GPU attacks (from Argon2d) and side-channel attacks (from Argon2i).
    let params = Params::new(ARGON2_M_COST, ARGON2_T_COST, ARGON2_P_COST, Some(ARGON2_OUTPUT_LEN))
        .map_err(|e| MeshError::Internal(format!("argon2 params error: {e}")))?;

    // Construct the Argon2id hasher with the configured parameters.
    let argon2 = Argon2::new(Algorithm::Argon2id, Version::V0x13, params);

    // Allocate the output buffer for the hash.
    // 32 bytes is sufficient for comparison-based verification.
    let mut hash_output = vec![0u8; ARGON2_OUTPUT_LEN];

    // Perform the Argon2id computation over the passphrase and salt.
    // This is deliberately slow (memory-hard) to resist brute-force.
    argon2
        .hash_password_into(passphrase.as_bytes(), salt, &mut hash_output)
        .map_err(|e| MeshError::Internal(format!("argon2 hash error: {e}")))?;

    // Return the raw hash bytes for storage/comparison.
    Ok(hash_output)
}

/// Verify a passphrase against a stored Argon2id hash.
///
/// Re-derives the hash from the candidate passphrase using the same
/// salt and compares it to the stored hash in constant time.
///
/// # Arguments
///
/// * `candidate` — the passphrase to verify.
/// * `salt` — the 16-byte salt used when the hash was created.
/// * `stored_hash` — the previously computed Argon2id hash to compare against.
///
/// # Errors
///
/// Returns `MeshError::Internal` if the Argon2id computation fails.
pub fn verify_passphrase_hash(
    candidate: &str,
    salt: &[u8; 16],
    stored_hash: &[u8],
) -> Result<bool, MeshError> {
    // Re-derive the hash from the candidate passphrase with the same salt.
    // The Argon2id parameters must match what was used during creation.
    let candidate_hash = hash_key_change_passphrase(candidate, salt)?;

    // Use constant-time comparison to prevent timing side-channels.
    // An attacker observing response times should not learn whether
    // individual bytes of the hash matched.
    Ok(constant_time_eq(&candidate_hash, stored_hash))
}

/// Constant-time byte comparison to prevent timing side-channels.
///
/// Compares two byte slices in a way that takes the same amount of
/// time regardless of how many bytes match. Critical for comparing
/// hashes where timing leaks could reveal partial matches.
fn constant_time_eq(a: &[u8], b: &[u8]) -> bool {
    // Different lengths are immediately unequal, but we still compare
    // to avoid leaking information about the length difference.
    if a.len() != b.len() {
        return false;
    }

    // XOR all bytes and accumulate — a difference in any byte sets
    // bits in the accumulator. The final result is 0 only if all match.
    let mut diff = 0u8;
    for (x, y) in a.iter().zip(b.iter()) {
        diff |= x ^ y;
    }

    // Zero diff means all bytes matched; non-zero means at least one differed.
    diff == 0
}

// ---------------------------------------------------------------------------
// RNG import for salt generation
// ---------------------------------------------------------------------------

use rand_core::RngCore;

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    /// Helper: generate a deterministic Ed25519 keypair from a seed byte.
    /// Returns (secret_key, public_key) as 32-byte arrays.
    fn test_keypair(seed: u8) -> ([u8; 32], [u8; 32]) {
        // Use the seed byte repeated 32 times as the secret key.
        let secret = [seed; 32];
        // Derive the public key from the secret key.
        let signing_key = ed25519_dalek::SigningKey::from_bytes(&secret);
        let public = signing_key.verifying_key().to_bytes();
        (secret, public)
    }

    /// Helper: create a key change request with full control over parameters.
    /// Builds the request manually to avoid SystemTime dependency in tests.
    fn make_test_request(
        old_secret: Option<&[u8; 32]>,
        old_pub: &[u8; 32],
        new_ed_pub: &[u8; 32],
        new_x25519_pub: &[u8; 32],
        timestamp: u64,
        passphrase: Option<(&str, &[u8; 16])>,
    ) -> KeyChangeRequest {
        // Build the signed message: new_ed_pub || new_x25519_pub || timestamp.
        let mut sign_message = Vec::with_capacity(72);
        sign_message.extend_from_slice(new_ed_pub);
        sign_message.extend_from_slice(new_x25519_pub);
        sign_message.extend_from_slice(&timestamp.to_le_bytes());

        // Sign with the old key if available.
        let old_key_signature = old_secret.map(|secret| {
            signing::sign(secret, DOMAIN_KEY_CHANGE, &sign_message)
        });

        // Hash the passphrase if provided.
        let (passphrase_hash, passphrase_salt) = match passphrase {
            Some((phrase, salt)) => {
                let hash = hash_key_change_passphrase(phrase, salt)
                    .expect("test passphrase hashing should not fail");
                (Some(hash), Some(*salt))
            }
            None => (None, None),
        };

        // Compute the expiry time for the 72-hour grace period.
        let expires_at = timestamp + GRACE_PERIOD_SECS;

        // Assemble the request with all fields populated.
        KeyChangeRequest {
            peer_id: PeerId::from_ed25519_pub(old_pub),
            old_ed_pub: *old_pub,
            new_ed_pub: *new_ed_pub,
            new_x25519_pub: *new_x25519_pub,
            old_key_signature,
            passphrase_hash,
            passphrase_salt,
            requested_at: timestamp,
            status: KeyChangeStatus::Pending { expires_at },
        }
    }

    // -----------------------------------------------------------------------
    // Happy path: key change with old key signature
    // -----------------------------------------------------------------------

    #[test]
    fn test_key_change_with_old_key_signature() {
        // Scenario: peer still has old key, signs the new keys.
        let (old_secret, old_pub) = test_keypair(0x11);
        let (_, new_ed_pub) = test_keypair(0x22);
        let new_x25519_pub = [0x33; 32];
        let timestamp = 1_700_000_000u64;

        // Create the request with old key signature.
        let request = make_test_request(
            Some(&old_secret),
            &old_pub,
            &new_ed_pub,
            &new_x25519_pub,
            timestamp,
            None,
        );

        // Signature field should be populated.
        assert!(
            request.old_key_signature.is_some(),
            "old_key_signature must be present when old_secret is provided"
        );

        // Validate: should return CryptographicProof since the old key signed.
        let result = validate_key_change(&request, &old_pub);
        assert!(result.is_ok(), "validation should succeed");
        assert_eq!(
            result.expect("checked above"),
            KeyChangeValidation::CryptographicProof,
            "must return CryptographicProof when old key signature is valid"
        );
    }

    // -----------------------------------------------------------------------
    // Passphrase-only key change
    // -----------------------------------------------------------------------

    #[test]
    fn test_key_change_with_passphrase_only() {
        // Scenario: old key is lost, but peer knows the shared passphrase.
        let (_, old_pub) = test_keypair(0x11);
        let (_, new_ed_pub) = test_keypair(0x22);
        let new_x25519_pub = [0x33; 32];
        let timestamp = 1_700_000_000u64;
        let salt = [0xAA; 16];

        // Create request without old key but with passphrase.
        let mut request = make_test_request(
            None,
            &old_pub,
            &new_ed_pub,
            &new_x25519_pub,
            timestamp,
            Some(("my-shared-secret", &salt)),
        );
        // The old_ed_pub should be zeroed since old key is unavailable.
        request.old_ed_pub = [0u8; 32];

        // Validate: should return PassphraseProof.
        let result = validate_key_change(&request, &old_pub);
        assert!(result.is_ok(), "validation should succeed for passphrase proof");
        assert_eq!(
            result.expect("checked above"),
            KeyChangeValidation::PassphraseProof,
            "must return PassphraseProof when only passphrase hash is present"
        );
    }

    // -----------------------------------------------------------------------
    // No proof key change (requires manual acceptance)
    // -----------------------------------------------------------------------

    #[test]
    fn test_key_change_with_no_proof() {
        // Scenario: old key lost, no passphrase set up — worst case.
        let (_, old_pub) = test_keypair(0x11);
        let (_, new_ed_pub) = test_keypair(0x22);
        let new_x25519_pub = [0x33; 32];
        let timestamp = 1_700_000_000u64;

        // Create request with no proof at all.
        let mut request = make_test_request(
            None,
            &old_pub,
            &new_ed_pub,
            &new_x25519_pub,
            timestamp,
            None,
        );
        // The old_ed_pub should be zeroed since old key is unavailable.
        request.old_ed_pub = [0u8; 32];

        // Validate: should return NoProof — contact must decide manually.
        let result = validate_key_change(&request, &old_pub);
        assert!(result.is_ok(), "validation should succeed (no proof is valid state)");
        assert_eq!(
            result.expect("checked above"),
            KeyChangeValidation::NoProof,
            "must return NoProof when neither signature nor passphrase is present"
        );
    }

    // -----------------------------------------------------------------------
    // 72-hour expiry handling
    // -----------------------------------------------------------------------

    #[test]
    fn test_72h_expiry_auto_accepts() {
        // Create a pending request with a known timestamp.
        let (_, old_pub) = test_keypair(0x11);
        let (_, new_ed_pub) = test_keypair(0x22);
        let timestamp = 1_700_000_000u64;
        let expires_at = timestamp + GRACE_PERIOD_SECS;

        let mut request = make_test_request(
            None, &old_pub, &new_ed_pub, &[0x33; 32], timestamp, None,
        );

        // Before expiry — should remain Pending.
        check_key_change_expiry(&mut request, expires_at - 1);
        assert!(
            matches!(request.status, KeyChangeStatus::Pending { .. }),
            "must remain Pending before the 72h window closes"
        );

        // At exactly the expiry time — should auto-accept.
        check_key_change_expiry(&mut request, expires_at);
        assert_eq!(
            request.status,
            KeyChangeStatus::AutoAccepted,
            "must auto-accept when the 72h grace period expires"
        );
    }

    #[test]
    fn test_72h_expiry_does_not_affect_accepted() {
        // Once accepted, expiry check should be a no-op.
        let (_, old_pub) = test_keypair(0x11);
        let (_, new_ed_pub) = test_keypair(0x22);
        let timestamp = 1_700_000_000u64;

        let mut request = make_test_request(
            None, &old_pub, &new_ed_pub, &[0x33; 32], timestamp, None,
        );

        // Accept the request manually before expiry.
        accept_key_change(&mut request);
        assert_eq!(request.status, KeyChangeStatus::Accepted);

        // Expiry check should not change the Accepted status.
        check_key_change_expiry(&mut request, timestamp + GRACE_PERIOD_SECS + 1000);
        assert_eq!(
            request.status,
            KeyChangeStatus::Accepted,
            "expiry check must not override an explicit acceptance"
        );
    }

    #[test]
    fn test_72h_expiry_does_not_affect_rejected() {
        // Once rejected, expiry check should be a no-op.
        let (_, old_pub) = test_keypair(0x11);
        let (_, new_ed_pub) = test_keypair(0x22);
        let timestamp = 1_700_000_000u64;

        let mut request = make_test_request(
            None, &old_pub, &new_ed_pub, &[0x33; 32], timestamp, None,
        );

        // Reject the request before expiry.
        reject_key_change(&mut request);
        assert_eq!(request.status, KeyChangeStatus::Rejected);

        // Expiry check should not change the Rejected status.
        check_key_change_expiry(&mut request, timestamp + GRACE_PERIOD_SECS + 1000);
        assert_eq!(
            request.status,
            KeyChangeStatus::Rejected,
            "expiry check must not override an explicit rejection"
        );
    }

    // -----------------------------------------------------------------------
    // Invalid old key signature rejection
    // -----------------------------------------------------------------------

    #[test]
    fn test_invalid_old_key_signature_rejected() {
        // Scenario: attacker forges a key change with a bad signature.
        let (_, old_pub) = test_keypair(0x11);
        let (_, new_ed_pub) = test_keypair(0x22);
        let new_x25519_pub = [0x33; 32];
        let timestamp = 1_700_000_000u64;

        // Create request with a forged (garbage) signature.
        let mut request = make_test_request(
            None, &old_pub, &new_ed_pub, &new_x25519_pub, timestamp, None,
        );
        // Inject a forged signature — 64 random bytes that won't verify.
        request.old_ed_pub = old_pub;
        request.old_key_signature = Some(vec![0xDE; 64]);

        // Validate: should return InvalidSignature error.
        let result = validate_key_change(&request, &old_pub);
        assert!(result.is_err(), "forged signature must be rejected");
        assert!(
            matches!(result.unwrap_err(), MeshError::InvalidSignature),
            "error must be InvalidSignature for a forged signature"
        );
    }

    #[test]
    fn test_mismatched_old_key_rejected() {
        // Scenario: request claims a different old key than what we have.
        let (old_secret, _old_pub) = test_keypair(0x11);
        let (_, different_pub) = test_keypair(0x99);
        let (_, new_ed_pub) = test_keypair(0x22);
        let timestamp = 1_700_000_000u64;

        // Create request signed by old_secret but claiming different_pub.
        let mut request = make_test_request(
            Some(&old_secret),
            &different_pub,
            &new_ed_pub,
            &[0x33; 32],
            timestamp,
            None,
        );
        // Override old_ed_pub to the wrong key (not matching known_old_pub).
        request.old_ed_pub = different_pub;

        // Our stored key is old_pub, but request claims different_pub.
        let (_, our_stored_pub) = test_keypair(0x11);
        let result = validate_key_change(&request, &our_stored_pub);
        assert!(result.is_err(), "mismatched old key must be rejected");
        assert!(
            matches!(result.unwrap_err(), MeshError::InvalidKey(_)),
            "error must be InvalidKey for mismatched old public key"
        );
    }

    // -----------------------------------------------------------------------
    // Wrong passphrase rejection
    // -----------------------------------------------------------------------

    #[test]
    fn test_wrong_passphrase_rejected() {
        // Test that a wrong passphrase produces a different hash.
        let salt = [0xBB; 16];

        // Hash the correct passphrase.
        let correct_hash = hash_key_change_passphrase("correct-phrase", &salt)
            .expect("hashing should succeed");

        // Verify with the wrong passphrase — should not match.
        let wrong_match = verify_passphrase_hash("wrong-phrase", &salt, &correct_hash)
            .expect("verification should not error");
        assert!(
            !wrong_match,
            "wrong passphrase must not match the stored hash"
        );

        // Verify with the correct passphrase — should match.
        let correct_match = verify_passphrase_hash("correct-phrase", &salt, &correct_hash)
            .expect("verification should not error");
        assert!(
            correct_match,
            "correct passphrase must match the stored hash"
        );
    }

    // -----------------------------------------------------------------------
    // Accept and reject actions
    // -----------------------------------------------------------------------

    #[test]
    fn test_accept_key_change() {
        let (_, old_pub) = test_keypair(0x11);
        let (_, new_ed_pub) = test_keypair(0x22);
        let timestamp = 1_700_000_000u64;

        let mut request = make_test_request(
            None, &old_pub, &new_ed_pub, &[0x33; 32], timestamp, None,
        );

        // Initially Pending.
        assert!(matches!(request.status, KeyChangeStatus::Pending { .. }));

        // Accept transitions to Accepted.
        accept_key_change(&mut request);
        assert_eq!(request.status, KeyChangeStatus::Accepted);

        // Accepting again is a no-op (idempotent).
        accept_key_change(&mut request);
        assert_eq!(request.status, KeyChangeStatus::Accepted);
    }

    #[test]
    fn test_reject_key_change() {
        let (_, old_pub) = test_keypair(0x11);
        let (_, new_ed_pub) = test_keypair(0x22);
        let timestamp = 1_700_000_000u64;

        let mut request = make_test_request(
            None, &old_pub, &new_ed_pub, &[0x33; 32], timestamp, None,
        );

        // Initially Pending.
        assert!(matches!(request.status, KeyChangeStatus::Pending { .. }));

        // Reject transitions to Rejected.
        reject_key_change(&mut request);
        assert_eq!(request.status, KeyChangeStatus::Rejected);

        // Rejecting again is a no-op (idempotent).
        reject_key_change(&mut request);
        assert_eq!(request.status, KeyChangeStatus::Rejected);
    }

    // -----------------------------------------------------------------------
    // Passphrase hashing determinism
    // -----------------------------------------------------------------------

    #[test]
    fn test_passphrase_hash_deterministic() {
        // Same passphrase + same salt must always produce the same hash.
        let salt = [0xCC; 16];
        let hash1 = hash_key_change_passphrase("test-passphrase", &salt)
            .expect("first hash should succeed");
        let hash2 = hash_key_change_passphrase("test-passphrase", &salt)
            .expect("second hash should succeed");

        assert_eq!(
            hash1, hash2,
            "same passphrase and salt must produce identical hashes"
        );
        assert_eq!(hash1.len(), ARGON2_OUTPUT_LEN, "hash must be 32 bytes");
    }

    #[test]
    fn test_passphrase_hash_different_salts() {
        // Same passphrase with different salts must produce different hashes.
        let salt_a = [0xAA; 16];
        let salt_b = [0xBB; 16];
        let hash_a = hash_key_change_passphrase("same-passphrase", &salt_a)
            .expect("hash A should succeed");
        let hash_b = hash_key_change_passphrase("same-passphrase", &salt_b)
            .expect("hash B should succeed");

        assert_ne!(
            hash_a, hash_b,
            "different salts must produce different hashes"
        );
    }

    // -----------------------------------------------------------------------
    // Constant-time comparison
    // -----------------------------------------------------------------------

    #[test]
    fn test_constant_time_eq() {
        // Equal slices must return true.
        assert!(constant_time_eq(&[1, 2, 3], &[1, 2, 3]));

        // Different slices must return false.
        assert!(!constant_time_eq(&[1, 2, 3], &[1, 2, 4]));

        // Different lengths must return false.
        assert!(!constant_time_eq(&[1, 2], &[1, 2, 3]));

        // Empty slices are equal.
        assert!(constant_time_eq(&[], &[]));
    }

    // -----------------------------------------------------------------------
    // Serde round-trip
    // -----------------------------------------------------------------------

    #[test]
    fn test_key_change_request_serde_roundtrip() {
        // Verify the request can be serialized to JSON and back.
        let (old_secret, old_pub) = test_keypair(0x11);
        let (_, new_ed_pub) = test_keypair(0x22);
        let timestamp = 1_700_000_000u64;

        let request = make_test_request(
            Some(&old_secret),
            &old_pub,
            &new_ed_pub,
            &[0x33; 32],
            timestamp,
            None,
        );

        // Serialize to JSON.
        let json = serde_json::to_string(&request)
            .expect("serialization should succeed");

        // Deserialize back.
        let recovered: KeyChangeRequest = serde_json::from_str(&json)
            .expect("deserialization should succeed");

        // Verify key fields survived the round-trip.
        assert_eq!(recovered.peer_id, request.peer_id);
        assert_eq!(recovered.old_ed_pub, request.old_ed_pub);
        assert_eq!(recovered.new_ed_pub, request.new_ed_pub);
        assert_eq!(recovered.new_x25519_pub, request.new_x25519_pub);
        assert_eq!(recovered.requested_at, request.requested_at);
    }

    // -----------------------------------------------------------------------
    // Grace period constant validation
    // -----------------------------------------------------------------------

    #[test]
    fn test_grace_period_is_72_hours() {
        // Validate the constant matches the spec requirement of 72 hours.
        assert_eq!(
            GRACE_PERIOD_SECS,
            72 * 60 * 60,
            "grace period must be exactly 72 hours in seconds"
        );
    }
}
