//! MeshPacket — the on-wire envelope for all routed mesh traffic (§6.5).
//!
//! Every application payload is wrapped in a `MeshPacket` before it enters
//! the routing layer. The packet carries:
//!
//! - Source and destination device addresses
//! - A unique packet ID for deduplication (§6.6)
//! - A TTL to prevent forwarding loops
//! - The payload (application-layer encrypted bytes)
//!
//! Intermediate nodes see the outer `MeshPacket` fields but NOT the payload,
//! which is application-layer encrypted end-to-end.

use serde::{Deserialize, Serialize};

use crate::routing::table::DeviceAddress;

// ---------------------------------------------------------------------------
// PacketKind
// ---------------------------------------------------------------------------

/// What kind of payload the MeshPacket carries.
///
/// Determines how the receiving node processes the payload after delivery.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
// Begin the block scope.
// PacketKind — variant enumeration.
// Match exhaustively to handle every protocol state.
// PacketKind — variant enumeration.
// Match exhaustively to handle every protocol state.
pub enum PacketKind {
    /// An encrypted message payload (Double Ratchet ciphertext, §7.2).
    Message,
    /// A reachability announcement to be processed by AnnouncementProcessor (§6.2).
    // Execute this protocol step.
    // Execute this protocol step.
    RouteAnnouncement,
    /// A keepalive / heartbeat packet.
    // Execute this protocol step.
    // Execute this protocol step.
    Keepalive,
    /// A raw data payload (file transfer chunk, §9).
    Data,
    /// A call signalling frame (offer / answer / hangup, §10).
    // Execute this protocol step.
    // Execute this protocol step.
    CallSignal,
}

// ---------------------------------------------------------------------------
// MeshPacket
// ---------------------------------------------------------------------------

/// The outer envelope for all routed mesh traffic.
///
/// Designed to be compact and serialisable as JSON (for clearnet TCP)
/// or as CBOR/binary (for RF/BLE transports — future work).
#[derive(Clone, Debug, Serialize, Deserialize)]
// Begin the block scope.
// MeshPacket — protocol data structure (see field-level docs).
// Invariants are enforced at construction time.
// MeshPacket — protocol data structure (see field-level docs).
// Invariants are enforced at construction time.
pub struct MeshPacket {
    /// Protocol version. Must be 1 for this implementation.
    // Execute this protocol step.
    // Execute this protocol step.
    pub version: u8,

    /// Unique 32-byte packet ID (random, generated by originator).
    /// Used by intermediate nodes to detect and drop duplicates (§6.6).
    #[serde(with = "hex_bytes32")]
    /// The packet id for this instance.
    // Execute this protocol step.
    // Execute this protocol step.
    pub packet_id: [u8; 32],

    /// Source device address (originator's identity key hash).
    #[serde(with = "hex_bytes32")]
    /// The source for this instance.
    // Execute this protocol step.
    // Execute this protocol step.
    pub source: [u8; 32],

    /// Destination device address.
    #[serde(with = "hex_bytes32")]
    /// The destination for this instance.
    // Execute this protocol step.
    // Execute this protocol step.
    pub destination: [u8; 32],

    /// Time-to-live: decremented at each hop. Packet is dropped if TTL == 0.
    /// Prevents forwarding loops in case of stale routing state.
    // Execute this protocol step.
    // Execute this protocol step.
    pub ttl: u8,

    /// What type of payload this is.
    // Execute this protocol step.
    // Execute this protocol step.
    pub kind: PacketKind,

    /// Application-layer encrypted payload (hex-encoded).
    /// End-to-end encrypted — intermediate nodes cannot read this.
    // Execute this protocol step.
    // Execute this protocol step.
    pub payload_hex: String,

    /// Unix timestamp when the packet was originated.
    // Execute this protocol step.
    // Execute this protocol step.
    pub timestamp: u64,
}

// Begin the block scope.
// MeshPacket implementation — core protocol logic.
// MeshPacket implementation — core protocol logic.
impl MeshPacket {
    /// Maximum TTL. Packets with a higher hop count than this are dropped.
    // MAX_TTL — protocol constant.
    // Defined by the spec; must not change without a version bump.
    // MAX_TTL — protocol constant.
    // Defined by the spec; must not change without a version bump.
    pub const MAX_TTL: u8 = 16;

    /// Create a new outgoing MeshPacket.
    // Perform the 'new' operation.
    // Errors are propagated to the caller via Result.
    // Perform the 'new' operation.
    // Errors are propagated to the caller via Result.
    pub fn new(
        // Process the current step in the protocol.
        // Execute this protocol step.
        // Execute this protocol step.
        source: [u8; 32],
        // Process the current step in the protocol.
        // Execute this protocol step.
        // Execute this protocol step.
        destination: [u8; 32],
        // Process the current step in the protocol.
        // Execute this protocol step.
        // Execute this protocol step.
        kind: PacketKind,
        // Execute this protocol step.
        // Execute this protocol step.
        payload: &[u8],
        // Execute this protocol step.
        // Execute this protocol step.
        now: u64,
    // Begin the block scope.
    // Execute this protocol step.
    // Execute this protocol step.
    ) -> Self {
        use rand_core::RngCore;
        // Unique identifier for lookup and deduplication.
        // Compute packet id for this protocol step.
        // Compute packet id for this protocol step.
        let mut packet_id = [0u8; 32];
        // OS-provided cryptographic random number generator.
        // Execute this protocol step.
        // Execute this protocol step.
        rand_core::OsRng.fill_bytes(&mut packet_id);

        // Assemble the instance from the computed fields.
        // Construct the instance from computed fields.
        // Construct the instance from computed fields.
        Self {
            // Execute this protocol step.
            // Execute this protocol step.
            version: 1,
            // Execute this protocol step.
            // Execute this protocol step.
            packet_id,
            source,
            // Execute this protocol step.
            // Execute this protocol step.
            destination,
            // Process the current step in the protocol.
            // Execute this protocol step.
            // Execute this protocol step.
            ttl: Self::MAX_TTL,
            kind,
            // Invoke the associated function.
            // Execute this protocol step.
            // Execute this protocol step.
            payload_hex: hex::encode(payload),
            // Execute this protocol step.
            // Execute this protocol step.
            timestamp: now,
        }
    }

    /// Decrement TTL and return whether this packet can still be forwarded.
    ///
    /// Returns `false` if the packet should be dropped.
    // Perform the 'decrement ttl' operation.
    // Errors are propagated to the caller via Result.
    // Perform the 'decrement ttl' operation.
    // Errors are propagated to the caller via Result.
    pub fn decrement_ttl(&mut self) -> bool {
        // Conditional branch based on the current state.
        // Guard: validate the condition before proceeding.
        // Guard: validate the condition before proceeding.
        if self.ttl == 0 {
            // Condition not met — return negative result.
            // Return to the caller.
            // Return to the caller.
            return false;
        }
        // Update the ttl to reflect the new state.
        // Advance ttl state.
        // Advance ttl state.
        self.ttl -= 1;
        true
    }

    /// Decode the hex-encoded payload back to bytes.
    // Perform the 'payload bytes' operation.
    // Errors are propagated to the caller via Result.
    // Perform the 'payload bytes' operation.
    // Errors are propagated to the caller via Result.
    pub fn payload_bytes(&self) -> Option<Vec<u8>> {
        // Check the operation outcome without consuming the error.
        // Execute this protocol step.
        // Execute this protocol step.
        hex::decode(&self.payload_hex).ok()
    }

    /// The destination as a `DeviceAddress`.
    // Perform the 'dest address' operation.
    // Errors are propagated to the caller via Result.
    // Perform the 'dest address' operation.
    // Errors are propagated to the caller via Result.
    pub fn dest_address(&self) -> DeviceAddress {
        // Process the current step in the protocol.
        // Execute this protocol step.
        // Execute this protocol step.
        DeviceAddress(self.destination)
    }

    /// The source as a `DeviceAddress`.
    // Perform the 'src address' operation.
    // Errors are propagated to the caller via Result.
    // Perform the 'src address' operation.
    // Errors are propagated to the caller via Result.
    pub fn src_address(&self) -> DeviceAddress {
        // Process the current step in the protocol.
        // Execute this protocol step.
        // Execute this protocol step.
        DeviceAddress(self.source)
    }
}

// ---------------------------------------------------------------------------
// Hex serde helper for [u8; 32]
// ---------------------------------------------------------------------------

// Sub-module: hex_bytes32 — see module-level docs for details.
// hex_bytes32 sub-module — see its own module-level docs.
// hex_bytes32 sub-module — see its own module-level docs.
mod hex_bytes32 {
    use serde::{Deserialize, Deserializer, Serializer};

    // Begin the block scope.
    // Perform the 'serialize' operation.
    // Errors are propagated to the caller via Result.
    // Perform the 'serialize' operation.
    // Errors are propagated to the caller via Result.
    pub fn serialize<S: Serializer>(bytes: &[u8; 32], s: S) -> Result<S::Ok, S::Error> {
        // Invoke the associated function.
        // Execute this protocol step.
        // Execute this protocol step.
        s.serialize_str(&hex::encode(bytes))
    }

    // Begin the block scope.
    // Perform the 'deserialize' operation.
    // Errors are propagated to the caller via Result.
    // Perform the 'deserialize' operation.
    // Errors are propagated to the caller via Result.
    pub fn deserialize<'de, D: Deserializer<'de>>(d: D) -> Result<[u8; 32], D::Error> {
        // Serialize to the wire format for transmission or storage.
        // Compute s for this protocol step.
        // Compute s for this protocol step.
        let s = String::deserialize(d)?;
        // Serialize to the wire format for transmission or storage.
        // Compute v for this protocol step.
        // Compute v for this protocol step.
        let v = hex::decode(&s).map_err(serde::de::Error::custom)?;
        // Validate the input length to prevent out-of-bounds access.
        // Guard: validate the condition before proceeding.
        // Guard: validate the condition before proceeding.
        if v.len() != 32 {
            // Reject with an explicit error for the caller to handle.
            // Return to the caller.
            // Return to the caller.
            return Err(serde::de::Error::custom("expected 32 bytes"));
        }
        // Execute the operation and bind the result.
        // Compute arr for this protocol step.
        // Compute arr for this protocol step.
        let mut arr = [0u8; 32];
        // Copy the raw bytes into the fixed-size target array.
        // Copy into the fixed-size buffer.
        // Copy into the fixed-size buffer.
        arr.copy_from_slice(&v);
        // Wrap the computed value in the success variant.
        // Success path — return the computed value.
        // Success path — return the computed value.
        Ok(arr)
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_packet_roundtrip() {
        let src = [0x11u8; 32];
        let dst = [0x22u8; 32];
        let payload = b"hello mesh";
        let now = 1_000_000u64;

        let pkt = MeshPacket::new(src, dst, PacketKind::Message, payload, now);
        let json = serde_json::to_string(&pkt).unwrap();
        let recovered: MeshPacket = serde_json::from_str(&json).unwrap();

        assert_eq!(recovered.version, 1);
        assert_eq!(recovered.destination, dst);
        assert_eq!(recovered.source, src);
        assert_eq!(recovered.payload_bytes().unwrap(), payload);
        assert_eq!(recovered.ttl, MeshPacket::MAX_TTL);
    }

    #[test]
    fn test_ttl_decrement() {
        let mut pkt = MeshPacket::new([0u8; 32], [1u8; 32], PacketKind::Keepalive, &[], 0);
        assert_eq!(pkt.ttl, MeshPacket::MAX_TTL);
        assert!(pkt.decrement_ttl());
        assert_eq!(pkt.ttl, MeshPacket::MAX_TTL - 1);
    }

    #[test]
    fn test_ttl_zero_drops() {
        let mut pkt = MeshPacket::new([0u8; 32], [1u8; 32], PacketKind::Keepalive, &[], 0);
        pkt.ttl = 0;
        assert!(!pkt.decrement_ttl());
    }
}
