//! MeshPacket — the on-wire envelope for all routed mesh traffic (§6.5).
//!
//! Every application payload is wrapped in a `MeshPacket` before it enters
//! the routing layer. The packet carries:
//!
//! - Source and destination device addresses
//! - A unique packet ID for deduplication (§6.6)
//! - A TTL to prevent forwarding loops
//! - The payload (application-layer encrypted bytes)
//!
//! Intermediate nodes see the outer `MeshPacket` fields but NOT the payload,
//! which is application-layer encrypted end-to-end.

use serde::{Deserialize, Serialize};

use crate::routing::table::DeviceAddress;

// ---------------------------------------------------------------------------
// PacketKind
// ---------------------------------------------------------------------------

/// What kind of payload the MeshPacket carries.
///
/// Determines how the receiving node processes the payload after delivery.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum PacketKind {
    /// An encrypted message payload (Double Ratchet ciphertext, §7.2).
    Message,
    /// A reachability announcement to be processed by AnnouncementProcessor (§6.2).
    RouteAnnouncement,
    /// A keepalive / heartbeat packet.
    Keepalive,
    /// A raw data payload (file transfer chunk, §9).
    Data,
    /// A call signalling frame (offer / answer / hangup, §10).
    CallSignal,
}

// ---------------------------------------------------------------------------
// MeshPacket
// ---------------------------------------------------------------------------

/// The outer envelope for all routed mesh traffic.
///
/// Designed to be compact and serialisable as JSON (for clearnet TCP)
/// or as CBOR/binary (for RF/BLE transports — future work).
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct MeshPacket {
    /// Protocol version. Must be 1 for this implementation.
    pub version: u8,

    /// Unique 32-byte packet ID (random, generated by originator).
    /// Used by intermediate nodes to detect and drop duplicates (§6.6).
    #[serde(with = "hex_bytes32")]
    pub packet_id: [u8; 32],

    /// Source device address (originator's identity key hash).
    #[serde(with = "hex_bytes32")]
    pub source: [u8; 32],

    /// Destination device address.
    #[serde(with = "hex_bytes32")]
    pub destination: [u8; 32],

    /// Time-to-live: decremented at each hop. Packet is dropped if TTL == 0.
    /// Prevents forwarding loops in case of stale routing state.
    pub ttl: u8,

    /// What type of payload this is.
    pub kind: PacketKind,

    /// Application-layer encrypted payload (hex-encoded).
    /// End-to-end encrypted — intermediate nodes cannot read this.
    pub payload_hex: String,

    /// Unix timestamp when the packet was originated.
    pub timestamp: u64,
}

impl MeshPacket {
    /// Maximum TTL. Packets with a higher hop count than this are dropped.
    pub const MAX_TTL: u8 = 16;

    /// Create a new outgoing MeshPacket.
    pub fn new(
        source: [u8; 32],
        destination: [u8; 32],
        kind: PacketKind,
        payload: &[u8],
        now: u64,
    ) -> Self {
        use rand_core::RngCore;
        let mut packet_id = [0u8; 32];
        rand_core::OsRng.fill_bytes(&mut packet_id);

        Self {
            version: 1,
            packet_id,
            source,
            destination,
            ttl: Self::MAX_TTL,
            kind,
            payload_hex: hex::encode(payload),
            timestamp: now,
        }
    }

    /// Decrement TTL and return whether this packet can still be forwarded.
    ///
    /// Returns `false` if the packet should be dropped.
    pub fn decrement_ttl(&mut self) -> bool {
        if self.ttl == 0 {
            return false;
        }
        self.ttl -= 1;
        true
    }

    /// Decode the hex-encoded payload back to bytes.
    pub fn payload_bytes(&self) -> Option<Vec<u8>> {
        hex::decode(&self.payload_hex).ok()
    }

    /// The destination as a `DeviceAddress`.
    pub fn dest_address(&self) -> DeviceAddress {
        DeviceAddress(self.destination)
    }

    /// The source as a `DeviceAddress`.
    pub fn src_address(&self) -> DeviceAddress {
        DeviceAddress(self.source)
    }
}

// ---------------------------------------------------------------------------
// Hex serde helper for [u8; 32]
// ---------------------------------------------------------------------------

mod hex_bytes32 {
    use serde::{Deserialize, Deserializer, Serializer};

    pub fn serialize<S: Serializer>(bytes: &[u8; 32], s: S) -> Result<S::Ok, S::Error> {
        s.serialize_str(&hex::encode(bytes))
    }

    pub fn deserialize<'de, D: Deserializer<'de>>(d: D) -> Result<[u8; 32], D::Error> {
        let s = String::deserialize(d)?;
        let v = hex::decode(&s).map_err(serde::de::Error::custom)?;
        if v.len() != 32 {
            return Err(serde::de::Error::custom("expected 32 bytes"));
        }
        let mut arr = [0u8; 32];
        arr.copy_from_slice(&v);
        Ok(arr)
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_packet_roundtrip() {
        let src = [0x11u8; 32];
        let dst = [0x22u8; 32];
        let payload = b"hello mesh";
        let now = 1_000_000u64;

        let pkt = MeshPacket::new(src, dst, PacketKind::Message, payload, now);
        let json = serde_json::to_string(&pkt).unwrap();
        let recovered: MeshPacket = serde_json::from_str(&json).unwrap();

        assert_eq!(recovered.version, 1);
        assert_eq!(recovered.destination, dst);
        assert_eq!(recovered.source, src);
        assert_eq!(recovered.payload_bytes().unwrap(), payload);
        assert_eq!(recovered.ttl, MeshPacket::MAX_TTL);
    }

    #[test]
    fn test_ttl_decrement() {
        let mut pkt = MeshPacket::new([0u8; 32], [1u8; 32], PacketKind::Keepalive, &[], 0);
        assert_eq!(pkt.ttl, MeshPacket::MAX_TTL);
        assert!(pkt.decrement_ttl());
        assert_eq!(pkt.ttl, MeshPacket::MAX_TTL - 1);
    }

    #[test]
    fn test_ttl_zero_drops() {
        let mut pkt = MeshPacket::new([0u8; 32], [1u8; 32], PacketKind::Keepalive, &[], 0);
        pkt.ttl = 0;
        assert!(!pkt.decrement_ttl());
    }
}
