//! Loop Prevention (§6.6)
//!
//! # What is Loop Prevention?
//!
//! In a mesh network, packets can potentially loop: A → B → C → A → B → ...
//! This wastes bandwidth, fills buffers, and can cause exponential
//! amplification. Loop prevention ensures every packet is forwarded
//! at most once by any given node.
//!
//! # Three Mechanisms
//!
//! The spec defines three complementary loop prevention mechanisms:
//!
//! 1. **Packet ID deduplication** — every packet carries a unique 32-byte
//!    ID. Each node maintains a bounded LRU cache of recently forwarded
//!    packet IDs. If a packet arrives with an ID that's already in the
//!    cache, it is silently dropped.
//!
//! 2. **Hop count bounding** — reachability announcements carry a hop_count
//!    field. If the hop_count exceeds the known mesh diameter, the
//!    announcement is discarded. This prevents announcement loops from
//!    inflating hop counts unboundedly. (Handled in announcement.rs.)
//!
//! 3. **Announcement ID deduplication** — reachability announcements carry
//!    a unique announcement_id. Nodes never forward an announcement
//!    they've already forwarded. (Also handled in announcement.rs.)
//!
//! This module implements mechanism #1: packet-level deduplication.
//!
//! # Deduplication Window
//!
//! The deduplication window is 1 hour (§6.5). This means a node remembers
//! packet IDs for 1 hour after forwarding them. After that, the ID is
//! evicted from the cache. This is long enough to prevent loops even in
//! high-latency mesh paths, but short enough to bound memory usage.
//!
//! # Bounded LRU Cache
//!
//! The cache is bounded by MAX_PACKET_CACHE entries. When full, the
//! oldest entry is evicted regardless of age. This provides a hard
//! memory ceiling: at 32 bytes per ID + 8 bytes timestamp = 40 bytes
//! per entry, 500K entries ≈ 20 MB.
//!
//! # Two Levels of Deduplication
//!
//! The spec distinguishes two deduplication scopes:
//!
//! - **Routing deduplication** (this module): 1-hour window, bounded LRU.
//!   Prevents forwarding loops. Packet IDs are evicted after the window.
//!
//! - **Message deduplication**: permanent, per-conversation. Prevents
//!   showing the same message twice to the user. Handled at the
//!   messaging layer, not here.

use std::collections::HashMap;

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/// Deduplication window in seconds (§6.5).
///
/// Packet IDs are remembered for 1 hour after forwarding.
/// This prevents loops even on high-latency paths (a packet
/// taking >1 hour to loop would be discarded by TTL anyway).
pub const DEDUP_WINDOW_SECS: u64 = 3600;

/// Maximum entries in the packet deduplication cache.
///
/// At 40 bytes per entry (32-byte ID + 8-byte timestamp),
/// 500K entries ≈ 20 MB. This is a hard memory ceiling.
///
/// In practice, a node forwarding 100 packets/second would
/// fill this in ~83 minutes, which is close to the 1-hour
/// dedup window — meaning entries expire before the cache fills.
pub const MAX_PACKET_CACHE: usize = 500_000;

// ---------------------------------------------------------------------------
// Packet ID
// ---------------------------------------------------------------------------

/// A 32-byte unique packet identifier.
///
/// Generated by the originating node using a CSPRNG. The packet ID
/// is included in the packet header and used for deduplication at
/// every forwarding node.
///
/// 256 bits of entropy means collision probability is negligible
/// even at billions of packets per day across the entire mesh.
#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
pub struct PacketId(pub [u8; 32]);

// ---------------------------------------------------------------------------
// Delivery Receipt
// ---------------------------------------------------------------------------

/// A signed delivery receipt (§6.5).
///
/// When a packet reaches its final destination, the recipient sends
/// back a delivery receipt. This serves two purposes:
///
/// 1. Confirms delivery to the sender (so it can stop retransmitting).
/// 2. Provides a tamper-proof record that the packet was received
///    (the signature prevents forging).
///
/// Delivery receipts travel back through the mesh using normal routing
/// (they're just packets themselves, with their own packet IDs).
#[derive(Clone, Debug)]
pub struct DeliveryReceipt {
    /// The packet ID of the delivered packet.
    pub packet_id: PacketId,

    /// The recipient's device address (who received it).
    pub recipient: [u8; 32],

    /// Unix timestamp when the packet was received.
    pub timestamp: u64,

    /// Ed25519 signature from the recipient.
    /// Signs: packet_id || recipient || timestamp.
    pub signature: Vec<u8>,
}

// ---------------------------------------------------------------------------
// Deduplication Cache
// ---------------------------------------------------------------------------

/// Bounded LRU packet deduplication cache.
///
/// Remembers recently forwarded packet IDs to prevent routing loops.
/// Each node in the mesh maintains one of these. When a packet arrives:
///
/// 1. Check if the packet ID is in the cache.
/// 2. If yes: drop the packet (it's a loop or duplicate).
/// 3. If no: forward the packet and add its ID to the cache.
///
/// The cache is bounded by MAX_PACKET_CACHE entries and entries
/// expire after DEDUP_WINDOW_SECS seconds.
pub struct DeduplicationCache {
    /// Map from packet ID to the timestamp when it was first seen.
    /// Using HashMap for O(1) lookup. LRU eviction is done during
    /// periodic garbage collection, not on every insert.
    entries: HashMap<PacketId, u64>,
}

impl DeduplicationCache {
    /// Create a new, empty deduplication cache.
    pub fn new() -> Self {
        Self {
            entries: HashMap::new(),
        }
    }

    /// Check if a packet has already been seen (and should be dropped).
    ///
    /// Returns `true` if the packet ID is in the cache (duplicate/loop).
    /// Returns `false` if this is a new packet.
    ///
    /// This is a read-only check — call `record()` after forwarding
    /// to add the ID to the cache.
    pub fn is_duplicate(&self, id: &PacketId) -> bool {
        self.entries.contains_key(id)
    }

    /// Record a packet ID as seen (just forwarded).
    ///
    /// Adds the packet ID to the cache with the current timestamp.
    /// If the cache is at capacity, expired entries are evicted first.
    /// If still at capacity, the oldest entry is evicted.
    ///
    /// `now`: current unix timestamp.
    pub fn record(&mut self, id: PacketId, now: u64) {
        // If at capacity, evict before inserting.
        if self.entries.len() >= MAX_PACKET_CACHE {
            self.evict(now);
        }

        self.entries.insert(id, now);
    }

    /// Check-and-record in one call.
    ///
    /// Returns `true` if the packet is a duplicate (should be dropped).
    /// Returns `false` if the packet is new (and records it).
    ///
    /// This is the most common usage pattern — called on every
    /// incoming packet before forwarding.
    pub fn check_and_record(&mut self, id: PacketId, now: u64) -> bool {
        if self.is_duplicate(&id) {
            return true;
        }
        self.record(id, now);
        false
    }

    /// Garbage-collect expired entries.
    ///
    /// Removes entries older than DEDUP_WINDOW_SECS.
    /// Should be called periodically (e.g., every 60 seconds)
    /// to keep memory usage bounded.
    pub fn gc(&mut self, now: u64) {
        self.entries.retain(|_, ts| {
            now.saturating_sub(*ts) <= DEDUP_WINDOW_SECS
        });
    }

    /// Number of entries currently in the cache.
    pub fn len(&self) -> usize {
        self.entries.len()
    }

    /// Whether the cache is empty.
    pub fn is_empty(&self) -> bool {
        self.entries.is_empty()
    }

    // -----------------------------------------------------------------------
    // Internal
    // -----------------------------------------------------------------------

    /// Evict entries to make room for new ones.
    ///
    /// First pass: remove entries older than the dedup window.
    /// Second pass (if still full): remove the single oldest entry.
    fn evict(&mut self, now: u64) {
        // First: remove expired entries.
        self.entries.retain(|_, ts| {
            now.saturating_sub(*ts) <= DEDUP_WINDOW_SECS
        });

        // If still at capacity, remove the oldest single entry.
        // This is O(n) but only runs when the cache is full AND
        // nothing has expired — a rare condition in practice.
        if self.entries.len() >= MAX_PACKET_CACHE {
            if let Some(oldest_key) = self
                .entries
                .iter()
                .min_by_key(|(_, ts)| *ts)
                .map(|(k, _)| *k)
            {
                self.entries.remove(&oldest_key);
            }
        }
    }
}

impl Default for DeduplicationCache {
    fn default() -> Self {
        Self::new()
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    /// Helper: create a PacketId from a single byte (repeated).
    fn pid(b: u8) -> PacketId {
        PacketId([b; 32])
    }

    #[test]
    fn test_new_cache_empty() {
        let cache = DeduplicationCache::new();
        assert!(cache.is_empty());
        assert_eq!(cache.len(), 0);
    }

    #[test]
    fn test_record_and_check() {
        let mut cache = DeduplicationCache::new();
        let id = pid(0x01);
        let now = 1000;

        // First time: not a duplicate.
        assert!(!cache.is_duplicate(&id));

        // Record it.
        cache.record(id, now);

        // Now it's a duplicate.
        assert!(cache.is_duplicate(&id));
        assert_eq!(cache.len(), 1);
    }

    #[test]
    fn test_check_and_record_combined() {
        let mut cache = DeduplicationCache::new();
        let id = pid(0x02);
        let now = 1000;

        // First call: not duplicate, records it.
        assert!(!cache.check_and_record(id, now));

        // Second call: duplicate.
        assert!(cache.check_and_record(id, now + 1));
    }

    #[test]
    fn test_gc_removes_expired() {
        let mut cache = DeduplicationCache::new();
        let now = 1000;

        // Insert some entries.
        cache.record(pid(0x01), now);
        cache.record(pid(0x02), now);
        cache.record(pid(0x03), now);

        assert_eq!(cache.len(), 3);

        // GC at a time when entries have expired.
        cache.gc(now + DEDUP_WINDOW_SECS + 1);

        assert_eq!(cache.len(), 0);
    }

    #[test]
    fn test_gc_preserves_fresh() {
        let mut cache = DeduplicationCache::new();
        let now = 1000;

        cache.record(pid(0x01), now);
        cache.record(pid(0x02), now + 100);

        // GC at a time when only the first entry is expired.
        // The second entry (at now + 100) should survive.
        let gc_time = now + DEDUP_WINDOW_SECS + 50;
        cache.gc(gc_time);

        // Entry at now is expired (age = DEDUP_WINDOW_SECS + 50 > window).
        // Entry at now+100 has age = DEDUP_WINDOW_SECS - 50, still fresh.
        assert_eq!(cache.len(), 1);
        assert!(!cache.is_duplicate(&pid(0x01)));
        assert!(cache.is_duplicate(&pid(0x02)));
    }

    #[test]
    fn test_different_ids_independent() {
        let mut cache = DeduplicationCache::new();
        let now = 1000;

        cache.record(pid(0x01), now);

        // Different IDs are independent.
        assert!(cache.is_duplicate(&pid(0x01)));
        assert!(!cache.is_duplicate(&pid(0x02)));
        assert!(!cache.is_duplicate(&pid(0xFF)));
    }

    #[test]
    fn test_delivery_receipt_fields() {
        // Just verify the struct can be constructed — the actual
        // signature verification will be tested in the crypto layer.
        let receipt = DeliveryReceipt {
            packet_id: pid(0xAA),
            recipient: [0xBB; 32],
            timestamp: 1000,
            signature: vec![0x42; 64],
        };

        assert_eq!(receipt.packet_id, pid(0xAA));
        assert_eq!(receipt.timestamp, 1000);
    }
}
